# Generated by Django 2.1.2 on 2018-11-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Item',
        ),
    ]
