# Generated by Django 2.1.5 on 2019-02-03 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlgraph',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
