# Generated by Django 2.1.5 on 2019-02-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0002_auto_20190203_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlgraph',
            name='sharedXMLGraph',
            field=models.TextField(null=True),
        ),
    ]
