# Generated by Django 2.1.5 on 2019-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0002_auto_20190120_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlgraph',
            name='title',
            field=models.CharField(default='Untitled Graph', max_length=100, null=True),
        ),
    ]
