# Generated by Django 2.1.2 on 2018-12-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0004_auto_20181225_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
