# Generated by Django 2.1.2 on 2018-12-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0005_member_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='title',
        ),
    ]
