# Generated by Django 2.1.2 on 2018-12-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0006_auto_20181230_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XMLGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XMLGraph', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='data',
        ),
        migrations.RemoveField(
            model_name='member',
            name='title',
        ),
        migrations.AddField(
            model_name='member',
            name='XMLGraph',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='fastcookapp.XMLGraph'),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='fastcookapp.Title'),
        ),
    ]
