# Generated by Django 2.1.2 on 2018-12-31 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0007_auto_20181231_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlgraph',
            name='title',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastcookapp.Title'),
        ),
    ]
