# Generated by Django 2.1.2 on 2019-01-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0008_xmlgraph_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmlgraph',
            name='XMLGraph',
        ),
        migrations.RemoveField(
            model_name='xmlgraph',
            name='title',
        ),
        migrations.AddField(
            model_name='title',
            name='XMLGraph',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastcookapp.XMLGraph'),
        ),
    ]
