# Generated by Django 2.1.2 on 2019-01-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0009_auto_20190101_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlgraph',
            name='XMLGraph',
            field=models.TextField(null=True),
        ),
    ]
