# Generated by Django 2.1.2 on 2019-01-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0011_auto_20190101_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmlgraph',
            old_name='XMLGraph',
            new_name='XMLgraph',
        ),
    ]
