# Generated by Django 2.1.2 on 2019-01-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0012_auto_20190101_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmlgraph',
            old_name='XMLgraph',
            new_name='XMLGraph',
        ),
    ]
