# Generated by Django 2.1.2 on 2019-01-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0013_auto_20190101_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='title',
        ),
        migrations.RemoveField(
            model_name='member',
            name='XMLGraph',
        ),
        migrations.AddField(
            model_name='member',
            name='XMLGraph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fastcookapp.XMLGraph'),
        ),
    ]
