# Generated by Django 2.1.5 on 2019-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0014_auto_20190103_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.TextField(null=True, unique=True),
        ),
    ]
