# Generated by Django 2.1.5 on 2019-01-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastcookapp', '0015_auto_20190118_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.TextField(default='Untitled Graph', null=True, unique=True),
        ),
    ]
